server:
  port: 9999
  servlet:
    context-path: /artisticconception

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/artisticconception?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis-plus:
  type-aliases-package: cn.mlgj.artisticconception.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    auto-mapping-behavior: full


